version: '3'
services:
    back:
        build: ./back_end
        container_name: back
        ports:
            - "4000:4000"
        links:
            - bdd
    bdd:
        image: mongo
        restart: always
        container_name: mango
        ports:
            - 27017:27017
    front:
        build: ./front_end
        container_name: front
        ports:
            - "3000:3000"